In [1]:
from transformers import pipeline

In [2]:
unmasker = pipeline('fill-mask', model='bert-base-multilingual-cased')

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [3]:
unmasker_ru = pipeline('fill-mask', model="DeepPavlov/rubert-base-cased")

Some weights of the model checkpoint at DeepPavlov/rubert-base-cased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [4]:
with open('citytest.txt', encoding='utf-8') as f:
    data = f.readlines()

['Димитровград, Пушкино и Обнинск - это [MASK].\n',
 'Железногорск, Набережные Челны и Камышин - это [MASK].\n',
 'Камышин, Серпухов и Таганрог - это [MASK].\n',
 'Волжский, Энгельс и Ачинск - это [MASK].\n',
 'Ачинск, Королёв и Батайск - это [MASK].\n',
 'Камышин, Серпухов и Ногинск - это [MASK].\n',
 'Салават, Стерлитамак и Сергиев Посад - это [MASK].\n',
 'Салават, Стерлитамак и Ковров - это [MASK].\n',
 'Димитровград, Пушкино и Ковров - это [MASK].\n',
 'Железногорск, Набережные Челны и Октябрьский - это [MASK].\n',
 '[MASK], например Энгельс, Димитровград или Ачинск.\n',
 '[MASK], например Энгельс, Димитровград или Батайск.\n',
 '[MASK], например Салават, Стерлитамак или Батайск.\n',
 '[MASK], например Королёв, Одинцово или Дзержинск.\n',
 '[MASK], например Волжский, Энгельс или Пушкино.\n',
 '[MASK], например Шахты, Нижний Тагил или Обнинск.\n',
 '[MASK], например Димитровград, Пушкино или Дербент.\n',
 '[MASK], например Набережные Челны, Волжский или Стерлитамак.\n',
 '[MASK], например Пушкино, Октябрьский или Керчь.\n',
 '[MASK], например Димитровград, Пушкино или Ногинск.\n']

In [5]:
import pandas as pd

In [6]:
cities_df = pd.DataFrame(columns=['sent','topic', 'masked', 'expect', 'pred1', 'pred2', 'pred3', 'pred4', 'pred5'])

In [7]:
cities_df

Empty DataFrame
Columns: [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
Index: []

In [8]:
cities_df_ru = pd.DataFrame(columns=['sent','topic', 'masked', 'expect', 'pred1', 'pred2', 'pred3', 'pred4', 'pred5'])

In [9]:
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'cities'
    masked = 'hyperonym'
    expect = 'города'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    cities_df.loc[len(cities_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    cities_df_ru.loc[len(cities_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [10]:
cities_df[0:2]

,sent,topic,masked,expect,pred1,pred2,pred3,pred4,pred5
0,"Димитровград, Пушкино и Обнинск - это [MASK].\n",cities,hyperonym,города,города,улицы,школы,группы,другие
1,"Железногорск, Набережные Челны и Камышин - это...",cities,hyperonym,города,другие,это,их,же,города

In [11]:
with open('city_hypon.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'cities'
    masked = 'hyponym'
    expect = 'Москва'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    cities_df.loc[len(cities_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    cities_df_ru.loc[len(cities_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [12]:
cities_df[20:22]

,sent,topic,masked,expect,pred1,pred2,pred3,pred4,pred5
20,"Елец, [MASK] и Артём.\n",cities,hyponym,Москва,Лев,Александр,Николай,Алексей,Антон
21,"Батайск, [MASK] и Таганрог.\n",cities,hyponym,Москва,Томск,Новосибирск,.,Екатеринбург,Красноярск

In [13]:
with open('city_comp_attrmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'cities'
    masked = 'attribute|comp'
    expect = 'площадь'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    cities_df.loc[len(cities_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    cities_df_ru.loc[len(cities_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [14]:
cities_df[30:32]

,sent,topic,masked,expect,pred1,pred2,pred3,pred4,pred5
30,"Чтобы понять, что больше, Елец или Обнинск, не...",cities,attribute|comp,площадь,название,имя,названия,города,имена
31,"Чтобы понять, что больше, Набережные Челны или...",cities,attribute|comp,площадь,больше,название,здесь,настоящее,нет

In [15]:
with open('city_comp_valmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'cities'
    masked = 'value|comp'
    expect = 'больше|меньше'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    cities_df.loc[len(cities_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    cities_df_ru.loc[len(cities_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [16]:
cities_df[60:62]

,sent,topic,masked,expect,pred1,pred2,pred3,pred4,pred5
60,"Чтобы понять, что [MASK], Октябрьский или Стер...",cities,value|comp,больше|меньше,это,площадь,улицы,улица,города
61,"Чтобы понять, что [MASK], Волжский или Камышин...",cities,value|comp,больше|меньше,это,он,площадь,реки,река

In [17]:
with open('city_single_attrmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'cities'
    masked = 'attribute|single'
    expect = 'площадь'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    cities_df.loc[len(cities_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    cities_df_ru.loc[len(cities_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [18]:
cities_df[84:86]

,sent,topic,masked,expect,pred1,pred2,pred3,pred4,pred5
84,"Город Стерлитамак большой, а значит у него бол...",cities,attribute|single,площадь,площадь,голова,слава,улица,земля
85,"Город Елец большой, а значит у него большая [M...",cities,attribute|single,площадь,слава,площадь,земля,деревня,улица

In [19]:
with open('city_single_valmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'cities'
    masked = 'value|single'
    expect = 'большой|маленький'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    cities_df.loc[len(cities_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    cities_df_ru.loc[len(cities_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [20]:
cities_df[104:106]

,sent,topic,masked,expect,pred1,pred2,pred3,pred4,pred5
104,"Город Димитровград [MASK], а значит у него бол...",cities,value|single,большой|маленький,площадь,большой,есть,сам,город
105,"Город Норильск [MASK], а значит у него большая...",cities,value|single,большой|маленький,площадь,город,есть,нет,сам

In [21]:
people_df = pd.DataFrame(columns=['sent','topic', 'masked', 'expect', 'pred1', 'pred2', 'pred3', 'pred4', 'pred5'])

In [22]:
people_df

Empty DataFrame
Columns: [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
Index: []

In [23]:
people_df_ru = pd.DataFrame(columns=['sent','topic', 'masked', 'expect', 'pred1', 'pred2', 'pred3', 'pred4', 'pred5'])

In [24]:
with open('people_hyper.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'people'
    masked = 'hyperonym'
    expect = 'люди'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    people_df.loc[len(people_df.index)] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    people_df_ru.loc[len(people_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [25]:
people_df[0:2]

,sent,topic,masked,expect,pred1,pred2,pred3,pred4,pred5
0,"Михаил Дмитриевич Прохоров, Дмитрий Евгеньевич...",people,hyperonym,люди,то,люди,другие,те,это
1,"Вагит Юсуфович Алекперов, Владимир Сергеевич Л...",people,hyperonym,люди,люди,другие,группы,то,те

In [26]:
with open('people_hypon.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'people'
    masked = 'hyponym'
    expect = 'Иван Иванов'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    people_df.loc[len(people_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    people_df_ru.loc[len(people_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [27]:
people_df[20:22]

,sent,topic,masked,expect,pred1,pred2,pred3,pred4,pred5
20,"Роман Аркадьевич Абрамович, [MASK] и Эдуард Юр...",people,hyponym,Иван Иванов,как,так,также,Роман,и
21,"Алишер Бурханович Усманов, [MASK] и Сергей Вик...",people,hyponym,Иван Иванов,также,как,Николай,и,Екатерина

In [28]:
with open('people_comp_attrmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'people'
    masked = 'attribute|comp'
    expect = 'состояние'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    people_df.loc[len(people_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    people_df_ru.loc[len(people_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [29]:
people_df[30:32]

,sent,topic,masked,expect,pred1,pred2,pred3,pred4,pred5
30,"Чтобы понять, кто богаче, Роман Аркадьевич Абр...",people,attribute|comp,состояние,имя,имена,хорошо,нет,»
31,"Чтобы понять, кто богаче, Геннадий Николаевич ...",people,attribute|comp,состояние,имя,имена,нет,науке,жизнь

In [30]:
with open('people_comp_valmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'people'
    masked = 'value|comp'
    expect = 'богаче|беднее'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    people_df.loc[len(people_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    people_df_ru.loc[len(people_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [31]:
people_df[60:62]

,sent,topic,masked,expect,pred1,pred2,pred3,pred4,pred5
60,"Чтобы понять, кто [MASK], Владимир Потанин или...",people,value|comp,богаче|беднее,он,это,тот,они,кто
61,"Чтобы понять, кто [MASK], Дмитрий Евгеньевич Р...",people,value|comp,богаче|беднее,он,тот,это,был,они

In [32]:
with open('people_single_attrmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'people'
    masked = 'attribute|single'
    expect = 'состояние'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    people_df.loc[len(people_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    people_df_ru.loc[len(people_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [33]:
people_df[84:86]

,sent,topic,masked,expect,pred1,pred2,pred3,pred4,pred5
84,"Геннадий Николаевич Тимченко богатый, а значит...",people,attribute|single,состояние,имя,внимание,влияние,значение,состояние
85,"Алишер Бурханович Усманов богатый, а значит у ...",people,attribute|single,состояние,имя,влияние,наследство,значение,внимание

In [34]:
with open('people_single_valmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'people'
    masked = 'value|single'
    expect = 'богатый|бедный'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    people_df.loc[len(people_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    people_df_ru.loc[len(people_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [35]:
people_df[104:106]

,sent,topic,masked,expect,pred1,pred2,pred3,pred4,pred5
104,"Владимир Потанин [MASK], а значит у него больш...",people,value|single,богатый|бедный,великий,-,.,был,много
105,"Эдуард Юрьевич Худайнатов [MASK], а значит у н...",people,value|single,богатый|бедный,##ич,-,##у,##т,был

In [39]:
cities_df.to_excel('cities_bert.xlsx', index=False)

In [40]:
people_df.to_excel('people_bert.xlsx', index=False)

In [41]:
cities_df_ru.to_excel('cities_bert_ru.xlsx', index=False)

In [42]:
people_df_ru.to_excel('people_bert_ru.xlsx', index=False)

In [53]:
metals_df = pd.DataFrame(columns=['sent','topic', 'masked', 'expect', 'pred1', 'pred2', 'pred3', 'pred4', 'pred5'])

In [54]:
metals_df

Empty DataFrame
Columns: [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
Index: []

In [55]:
metals_df_ru = pd.DataFrame(columns=['sent','topic', 'masked', 'expect', 'pred1', 'pred2', 'pred3', 'pred4', 'pred5'])

In [56]:
metals_df.size

0

In [57]:
with open('metals_hyper.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'metals'
    masked = 'hyperonym'
    expect = 'металлы'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    metals_df.loc[len(metals_df.index)] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    metals_df_ru.loc[len(metals_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [58]:
with open('metals_hypon.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'metals'
    masked = 'hyponym'
    expect = 'медь'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    metals_df.loc[len(metals_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    metals_df_ru.loc[len(metals_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [59]:
with open('metals_comp_attrmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'metals'
    masked = 'attribute|comp'
    expect = 'вес'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    metals_df.loc[len(metals_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    metals_df_ru.loc[len(metals_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [60]:
with open('metals_comp_valmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'metals'
    masked = 'value|comp'
    expect = 'тяжелее|легче'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    metals_df.loc[len(metals_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    metals_df_ru.loc[len(metals_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [61]:
with open('metals_single_attrmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'metals'
    masked = 'attribute|single'
    expect = 'вес'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    metals_df.loc[len(metals_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    metals_df_ru.loc[len(metals_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [62]:
with open('metals_single_valmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'metals'
    masked = 'value|single'
    expect = 'тяжелый|легкий'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    metals_df.loc[len(metals_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    metals_df_ru.loc[len(metals_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [64]:
metals_df.to_excel('metals_bert.xlsx', index=False)

In [66]:
metals_df_ru.to_excel('metals_bert_ru.xlsx', index=False)

In [67]:
names_df = pd.DataFrame(columns=['sent','topic', 'masked', 'expect', 'pred1', 'pred2', 'pred3', 'pred4', 'pred5'])

In [68]:
names_df_ru = pd.DataFrame(columns=['sent','topic', 'masked', 'expect', 'pred1', 'pred2', 'pred3', 'pred4', 'pred5'])

In [69]:
with open('names_hyper.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'names'
    masked = 'hyperonym'
    expect = 'люди'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    names_df.loc[len(names_df.index)] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    names_df_ru.loc[len(names_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [70]:
with open('names_hypon.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'names'
    masked = 'hyponym'
    expect = 'Иван'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    names_df.loc[len(names_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    names_df_ru.loc[len(names_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [71]:
with open('names_comp_attrmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'names'
    masked = 'attribute|comp'
    expect = 'состояние'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    names_df.loc[len(names_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    names_df_ru.loc[len(names_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [72]:
with open('names_comp_valmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'names'
    masked = 'value|comp'
    expect = 'богаче|беднее'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    names_df.loc[len(names_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    names_df_ru.loc[len(names_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [73]:
with open('names_single_attrmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'names'
    masked = 'attribute|single'
    expect = 'состояние'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    names_df.loc[len(names_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    names_df_ru.loc[len(names_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [74]:
with open('names_single_valmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'names'
    masked = 'value|single'
    expect = 'богатый|бедный'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    names_df.loc[len(names_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    names_df_ru.loc[len(names_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [75]:
names_df.to_excel('names_bert.xlsx', index=False)

In [76]:
names_df_ru.to_excel('names_bert_ru.xlsx', index=False)

In [77]:
names2_df = pd.DataFrame(columns=['sent','topic', 'masked', 'expect', 'pred1', 'pred2', 'pred3', 'pred4', 'pred5'])

In [78]:
names2_df_ru = pd.DataFrame(columns=['sent','topic', 'masked', 'expect', 'pred1', 'pred2', 'pred3', 'pred4', 'pred5'])

In [79]:
with open('names2_comp_attrmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'names2'
    masked = 'attribute|comp'
    expect = 'рост'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    names2_df.loc[len(names2_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    names2_df_ru.loc[len(names2_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [80]:
with open('names2_comp_valmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'names2'
    masked = 'value|comp'
    expect = 'выше|ниже'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    names2_df.loc[len(names2_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    names2_df_ru.loc[len(names2_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [81]:
with open('names2_single_attrmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'names2'
    masked = 'attribute|single'
    expect = 'рост'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    names2_df.loc[len(names2_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    names2_df_ru.loc[len(names2_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [82]:
with open('names2_single_valmasked.txt', encoding='utf-8') as f:
    data = f.readlines()
    
for d in data:
    res = unmasker(d)
    sent = d
    topic = 'names2'
    masked = 'value|single'
    expect = 'высокй|низкий'
    pred1 = res[0]['token_str']
    pred2 = res[1]['token_str']
    pred3 = res[2]['token_str']
    pred4 = res[3]['token_str']
    pred5 = res[4]['token_str']
    names2_df.loc[len(names2_df.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]
    
    res_ru = unmasker_ru(d)
    pred1 = res_ru[0]['token_str']
    pred2 = res_ru[1]['token_str']
    pred3 = res_ru[2]['token_str']
    pred4 = res_ru[3]['token_str']
    pred5 = res_ru[4]['token_str']
    names2_df_ru.loc[len(names2_df_ru.index )] = [sent, topic, masked, expect, pred1, pred2, pred3, pred4, pred5]

In [83]:
names2_df.to_excel('names2_bert.xlsx', index=False)

In [84]:
names2_df_ru.to_excel('names2_bert_ru.xlsx', index=False)